{
//'dateTimeFormat': 'iso8601',

'events' :[{'start':"1977",'durationEvent':false,'title':"Don Aase",'description':"Boston Red Sox"},
{'start':"1973",'durationEvent':false,'title':"Glenn Abbott",'description':"Oakland Athletics"},
{'start':"1993",'durationEvent':false,'title':"Kurt Abbott",'description':"Oakland Athletics"},
{'start':"1990",'durationEvent':false,'title':"Paul Abbott",'description':"Minnesota Twins"},
{'start':"1950",'durationEvent':false,'title':"Al Aber",'description':"Cleveland Indians"},
{'start':"1952",'durationEvent':false,'title':"Bill Abernathie",'description':"Cleveland Indians"},
{'start':"1963",'durationEvent':false,'title':"Ted Abernathy",'description':"Cleveland Indians"},
{'start':"1954",'durationEvent':false,'title':"Cal Abrams",'description':"Baltimore Orioles"},
{'start':"1983",'durationEvent':false,'title':"Jim Acker",'description':"Toronto Blue Jays"},
{'start':"1994",'durationEvent':false,'title':"Mark Acre",'description':"Oakland Athletics"},
{'start':"1958",'durationEvent':false,'title':"Jerry Adair",'description':"Baltimore Orioles"},
{'start':"1956",'durationEvent':false,'title':"Bobby Adams",'description':"Baltimore Orioles"},
{'start':"1977",'durationEvent':false,'title':"Bob Adams",'description':"Detroit Tigers"},
{'start':"1977",'durationEvent':false,'title':"Glenn Adams",'description':"Minnesota Twins"},
{'start':"1967",'durationEvent':false,'title':"Mike Adamson",'description':"Baltimore Orioles"},
{'start':"1972",'durationEvent':false,'title':"Mike Adams",'description':"Minnesota Twins"},
{'start':"1996",'durationEvent':false,'title':"Willie Adams",'description':"Oakland Athletics"},
{'start':"1963",'durationEvent':false,'title':"Joe Adcock",'description':"Cleveland Indians"},
{'start':"1990",'durationEvent':false,'title':"Troy Afenir",'description':"Oakland Athletics"},
{'start':"1962",'durationEvent':false,'title':"Tommie Agee",'description':"Cleveland Indians"},
{'start':"1954",'durationEvent':false,'title':"Harry Agganis",'description':"Boston Red Sox"},
{'start':"1986",'durationEvent':false,'title':"Juan Agosto",'description':"Minnesota Twins"},
{'start':"1989",'durationEvent':false,'title':"Luis Aguayo",'description':"Cleveland Indians"},
{'start':"1989",'durationEvent':false,'title':"Rick Aguilera",'description':"Minnesota Twins"},
{'start':"1955",'durationEvent':false,'title':"Hank Aguirre",'description':"Cleveland Indians"},
{'start':"1995",'durationEvent':false,'title':"Pat Ahearne",'description':"Detroit Tigers"},
{'start':"1984",'durationEvent':false,'title':"Willie Aikens",'description':"Toronto Blue Jays"},
{'start':"1979",'durationEvent':false,'title':"Danny Ainge",'description':"Toronto Blue Jays"},
{'start':"1986",'durationEvent':false,'title':"Darrel Akerfelds",'description':"Oakland Athletics"},
{'start':"1968",'durationEvent':false,'title':"Jack Aker",'description':"Oakland Athletics"},
{'start':"1931",'durationEvent':false,'title':"Bill Akers",'description':"Detroit Tigers"},
{'start':"1978",'durationEvent':false,'title':"Butch Alberts",'description':"Toronto Blue Jays"},
{'start':"1995",'durationEvent':false,'title':"Jose Alberro",'description':"Texas Rangers"},
{'start':"1973",'durationEvent':false,'title':"Vic Albury",'description':"Minnesota Twins"},
{'start':"1991",'durationEvent':false,'title':"Mike Aldrete",'description':"Cleveland Indians"},
{'start':"1990",'durationEvent':false,'title':"Scott Aldred",'description':"Detroit Tigers"},
{'start':"1990",'durationEvent':false,'title':"Jay Aldrich",'description':"Baltimore Orioles"},
{'start':"1955",'durationEvent':false,'title':"Bob Alexander",'description':"Baltimore Orioles"},
{'start':"1931",'durationEvent':false,'title':"Dale Alexander",'description':"Detroit Tigers"},
{'start':"1972",'durationEvent':false,'title':"Doyle Alexander",'description':"Baltimore Orioles"},
{'start':"1978",'durationEvent':false,'title':"Gary Alexander",'description':"Oakland Athletics"},
{'start':"1990",'durationEvent':false,'title':"Gerald Alexander",'description':"Texas Rangers"},
{'start':"1937",'durationEvent':false,'title':"Hugh Alexander",'description':"Cleveland Indians"},
{'start':"1975",'durationEvent':false,'title':"Matt Alexander",'description':"Oakland Athletics"},
{'start':"1992",'durationEvent':false,'title':"Manny Alexander",'description':"Baltimore Orioles"},
{'start':"1995",'durationEvent':false,'title':"Luis Alicea",'description':"Boston Red Sox"},
{'start':"1986",'durationEvent':false,'title':"Andy Allanson",'description':"Cleveland Indians"},
{'start':"1979",'durationEvent':false,'title':"Brian Allard",'description':"Texas Rangers"},
{'start':"1962",'durationEvent':false,'title':"Bernie Allen",'description':"Minnesota Twins"},
{'start':"1961",'durationEvent':false,'title':"Bob Allen",'description':"Cleveland Indians"}]
}