{
'dateTimeFormat': 'iso8601', 

'events' : [{'start':"1966",'durationEvent':false,'title':"Hank Aaron",'description':"Atlanta Braves"},
{'start':"1968",'durationEvent':false,'title':"Tommie Aaron",'description':"Atlanta Braves"},
{'start':"1999",'durationEvent':false,'title':"Jim Abbott",'description':"Milwaukee Brewers"},
{'start':"1998",'durationEvent':false,'title':"Kurt Abbott",'description':"Colorado Rockies"},
{'start':"1992",'durationEvent':false,'title':"Kyle Abbott",'description':"Philadelphia Phillies"},
{'start':"1966",'durationEvent':false,'title':"Ted Abernathy",'description':"Atlanta Braves"},
{'start':"1952",'durationEvent':false,'title':"Cal Abrams",'description':"Cincinnati Reds"},
{'start':"1996",'durationEvent':false,'title':"Bobby Abreu",'description':"Houston Astros"},
{'start':"1942",'durationEvent':false,'title':"Joe Abreu",'description':"Cincinnati Reds"},
{'start':"1995",'durationEvent':false,'title':"Juan Acevedo",'description':"Colorado Rockies"},
{'start':"1986",'durationEvent':false,'title':"Jim Acker",'description':"Atlanta Braves"},
{'start':"1956",'durationEvent':false,'title':"Tom Acker",'description':"Cincinnati Reds"},
{'start':"1975",'durationEvent':false,'title':"Cy Acosta",'description':"Philadelphia Phillies"},
{'start':"1970",'durationEvent':false,'title':"Ed Acosta",'description':"Pittsburgh Pirates"},
{'start':"1931",'durationEvent':false,'title':"Bob Adams",'description':"Philadelphia Phillies"},
{'start':"1946",'durationEvent':false,'title':"Bobby Adams",'description':"Cincinnati Reds"},
{'start':"1943",'durationEvent':false,'title':"Buster Adams",'description':"Philadelphia Phillies"},
{'start':"1998",'durationEvent':false,'title':"Joel Adamson",'description':"Arizona Diamondbacks"},
{'start':"1933",'durationEvent':false,'title':"Sparky Adams",'description':"Cincinnati Reds"},
{'start':"1950",'durationEvent':false,'title':"Joe Adcock",'description':"Cincinnati Reds"},
{'start':"1953",'durationEvent':false,'title':"Bob Addis",'description':"Pittsburgh Pirates"},
{'start':"1989",'durationEvent':false,'title':"Jim Adduci",'description':"Philadelphia Phillies"},
{'start':"1963",'durationEvent':false,'title':"Dave Adlesh",'description':"Houston Astros"},
{'start':"1987",'durationEvent':false,'title':"Troy Afenir",'description':"Houston Astros"},
{'start':"1973",'durationEvent':false,'title':"Tommie Agee",'description':"Houston Astros"},
{'start':"1987",'durationEvent':false,'title':"Juan Agosto",'description':"Houston Astros"},
{'start':"1980",'durationEvent':false,'title':"Luis Aguayo",'description':"Philadelphia Phillies"},
{'start':"1990",'durationEvent':false,'title':"Darrel Akerfelds",'description':"Philadelphia Phillies"},
{'start':"1974",'durationEvent':false,'title':"Jack Aker",'description':"Atlanta Braves"},
{'start':"1946",'durationEvent':false,'title':"Ed Albosta",'description':"Pittsburgh Pirates"},
{'start':"1947",'durationEvent':false,'title':"Jack Albright",'description':"Philadelphia Phillies"},
{'start':"1976",'durationEvent':false,'title':"Santo Alcala",'description':"Cincinnati Reds"},
{'start':"1993",'durationEvent':false,'title':"Scott Aldred",'description':"Colorado Rockies"},
{'start':"1989",'durationEvent':false,'title':"Jay Aldrich",'description':"Atlanta Braves"},
{'start':"1941",'durationEvent':false,'title':"Chuck Aleno",'description':"Cincinnati Reds"},
{'start':"1980",'durationEvent':false,'title':"Doyle Alexander",'description':"Atlanta Braves"},
{'start':"1981",'durationEvent':false,'title':"Gary Alexander",'description':"Pittsburgh Pirates"},
{'start':"1978",'durationEvent':false,'title':"Matt Alexander",'description':"Pittsburgh Pirates"},
{'start':"1937",'durationEvent':false,'title':"Bob Allen",'description':"Philadelphia Phillies"},
{'start':"1963",'durationEvent':false,'title':"Dick Allen",'description':"Philadelphia Phillies"},
{'start':"1934",'durationEvent':false,'title':"Ethan Allen",'description':"Philadelphia Phillies"},
{'start':"1996",'durationEvent':false,'title':"Jermaine Allensworth",'description':"Pittsburgh Pirates"},
{'start':"1963",'durationEvent':false,'title':"Gene Alley",'description':"Pittsburgh Pirates"},
{'start':"1954",'durationEvent':false,'title':"Gair Allie",'description':"Pittsburgh Pirates"},
{'start':"1985",'durationEvent':false,'title':"Bill Almon",'description':"Pittsburgh Pirates"},
{'start':"1966",'durationEvent':false,'title':"Sandy Alomar",'description':"Atlanta Braves"},
{'start':"1966",'durationEvent':false,'title':"Felipe Alou",'description':"Atlanta Braves"},
{'start':"1969",'durationEvent':false,'title':"Jesus Alou",'description':"Houston Astros"},
{'start':"1966",'durationEvent':false,'title':"Matty Alou",'description':"Pittsburgh Pirates"},
{'start':"1990",'durationEvent':false,'title':"Moises Alou",'description':"Pittsburgh Pirates"}

]
}